import Head from 'next/head'


export default function Home() {
  
  return (
    <div className="h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />            
      </Head>

      <main className="flex flex-col gap-20 items-center w-screen h-full p-8">
        <h2 className="text-2xl border-2 p-8">Sign-up to create a new account</h2>
        <h2 className="text-2xl border-2 p-8">Or sign-in to access your dashboard</h2>
      </main>

      
    </div>
  )
}
