import Head from 'next/head';
import { useAuthState } from "react-firebase-hooks/auth";
import { Breadcrumbs } from "@material-tailwind/react";
import { FaHome } from "react-icons/fa";
import { auth } from "../utils/firebase";
import { useRouter } from "next/router";

export default function Home() {
  const route = useRouter();
  const [user, loading] = useAuthState(auth);
  
  //Redirect when user logged in
  //if (user) { route.push('/dashboard') }
  
  //When no user, show instruction
  if (!user) {
    return (
      <div className="h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />            
      </Head>

        <main className="flex flex-col gap-20 items-center w-screen h-full p-8">
          <Breadcrumbs separator="/">
            <a href="/" className="opacity-80">
                <FaHome />                    
            </a>
          </Breadcrumbs>
        <h2 className="text-2xl border-2 p-8">Sign-up to create a new account</h2>
        <h2 className="text-2xl border-2 p-8">Or sign-in to access your dashboard</h2>
      </main>  
    </div>
    )
  }
}
